import type { LevelDefinition } from "../level";

export const LEVEL_03_DARK_TIDE_BRIDGE: LevelDefinition = {
  id: "dark-tide-bridge",
  name: "第三关：暗潮星桥",
  bounds: { x: 32, y: 18 },
  startPosition: { x: -30.4, y: -13.1 },
  startVelocity: { x: 4.6, y: 2.04 },
  goalMass: 48,
  goalShards: 22,
  planets: [
    {
      id: "void-cradle",
      name: "黑潮摇篮",
      role: "anchor",
      position: { x: -20.2, y: -8.6 },
      mass: 16.2,
      radius: 2.18,
      captureRadius: 7.35,
      palette: { base: "#31234f", accent: "#59e3ff", glow: "#a777ff" },
      hasRing: true,
    },
    {
      id: "cyan-lens",
      name: "青镜中枢",
      role: "anchor",
      position: { x: -13.3, y: 3.7 },
      mass: 22.5,
      radius: 1.96,
      captureRadius: 7.1,
      palette: { base: "#7df4e9", accent: "#476aff", glow: "#82fff4" },
      hasRing: true,
    },
    {
      id: "amber-furnace",
      name: "琥珀炉心",
      role: "anchor",
      position: { x: -4.2, y: -5.2 },
      mass: 30,
      radius: 1.86,
      captureRadius: 7.05,
      palette: { base: "#f4bd65", accent: "#ff6e74", glow: "#ffdc8a" },
      hasRing: true,
    },
    {
      id: "white-arch",
      name: "白冠拱门",
      role: "anchor",
      position: { x: 2.7, y: 6.4 },
      mass: 38.5,
      radius: 1.72,
      captureRadius: 6.85,
      palette: { base: "#fff6c8", accent: "#75d6ff", glow: "#fff9b8" },
    },
    {
      id: "blue-keel",
      name: "蓝脊航标",
      role: "anchor",
      position: { x: 11.5, y: -1.5 },
      mass: 46.2,
      radius: 1.58,
      captureRadius: 7.0,
      palette: { base: "#639cff", accent: "#9cffd0", glow: "#7bcaff" },
      hasRing: true,
    },
    {
      id: "red-pivot",
      name: "赤潮枢纽",
      role: "anchor",
      position: { x: 19.2, y: -9.3 },
      mass: 58,
      radius: 1.62,
      captureRadius: 7.25,
      palette: { base: "#ff695f", accent: "#5a1f58", glow: "#ff9a80" },
      hasRing: true,
    },
    {
      id: "aurora-crown",
      name: "极光王冠",
      role: "anchor",
      position: { x: 19.4, y: 7.4 },
      mass: 54,
      radius: 1.5,
      captureRadius: 6.9,
      palette: { base: "#96ffad", accent: "#5c7dff", glow: "#b4ffba" },
    },
    {
      id: "far-lantern",
      name: "远日灯塔",
      role: "anchor",
      position: { x: 27.2, y: 0.2 },
      mass: 68,
      radius: 1.7,
      captureRadius: 7.2,
      palette: { base: "#ffe08c", accent: "#ff7168", glow: "#fff0a4" },
      hasRing: true,
    },
    {
      id: "cold-splinter",
      name: "冷屑一号",
      role: "minor",
      position: { x: -24.2, y: -4.7 },
      mass: 0.32,
      radius: 0.38,
      captureRadius: 0,
      palette: { base: "#d7fbff", accent: "#66a8ff", glow: "#9df8ff" },
    },
    {
      id: "ice-bean",
      name: "碎冰豆",
      role: "minor",
      position: { x: -18.1, y: -2.0 },
      mass: 0.44,
      radius: 0.43,
      captureRadius: 0,
      palette: { base: "#baf4ff", accent: "#7a96ff", glow: "#aefaff" },
    },
    {
      id: "cyan-salt",
      name: "青盐片",
      role: "minor",
      position: { x: -16.5, y: -12.7 },
      mass: 0.58,
      radius: 0.5,
      captureRadius: 0,
      palette: { base: "#7ff2ca", accent: "#246e99", glow: "#84ffd9" },
    },
    {
      id: "rose-dust",
      name: "粉尘核",
      role: "minor",
      position: { x: -10.2, y: -1.4 },
      mass: 0.72,
      radius: 0.56,
      captureRadius: 0,
      palette: { base: "#ff9bb2", accent: "#91316f", glow: "#ffb4c5" },
    },
    {
      id: "black-grain",
      name: "玄砂珠",
      role: "minor",
      position: { x: -15.5, y: 8.8 },
      mass: 0.88,
      radius: 0.62,
      captureRadius: 0,
      palette: { base: "#2b2448", accent: "#9cf7ff", glow: "#b17cff" },
    },
    {
      id: "verdigris-eye",
      name: "铜绿眼",
      role: "minor",
      position: { x: -6.6, y: 1.8 },
      mass: 1.05,
      radius: 0.7,
      captureRadius: 0,
      palette: { base: "#7df0c2", accent: "#d99147", glow: "#8fffd5" },
    },
    {
      id: "dusk-orb",
      name: "薄暮球",
      role: "minor",
      position: { x: -0.2, y: -9.0 },
      mass: 1.24,
      radius: 0.78,
      captureRadius: 0,
      palette: { base: "#f0a66c", accent: "#6b2a78", glow: "#ffc88f" },
    },
    {
      id: "frost-ringlet",
      name: "霜环粒",
      role: "minor",
      position: { x: -2.0, y: 1.1 },
      mass: 1.46,
      radius: 0.84,
      captureRadius: 0,
      palette: { base: "#d8ffff", accent: "#6587ff", glow: "#e9ffff" },
    },
    {
      id: "blue-flame-seed",
      name: "蓝焰种",
      role: "minor",
      position: { x: 1.02, y: 2.55 },
      mass: 1.7,
      radius: 0.91,
      captureRadius: 0,
      orbitPath: {
        center: { x: 2.7, y: 6.4 },
        radius: 4.2,
        phase: 4.3,
        angularSpeed: 0.28,
      },
      palette: { base: "#5d8fff", accent: "#27e3ff", glow: "#88a9ff" },
    },
    {
      id: "glow-stone",
      name: "霞光石",
      role: "minor",
      position: { x: 0.23, y: 9.79 },
      mass: 1.96,
      radius: 0.98,
      captureRadius: 0,
      orbitPath: {
        center: { x: 2.7, y: 6.4 },
        radius: 4.2,
        phase: 2.2,
        angularSpeed: 0.28,
      },
      palette: { base: "#ffd488", accent: "#ee6f91", glow: "#ffe5a4" },
    },
    {
      id: "red-nail",
      name: "赤钉",
      role: "minor",
      position: { x: 6.88, y: 6.82 },
      mass: 2.25,
      radius: 1.05,
      captureRadius: 0,
      orbitPath: {
        center: { x: 2.7, y: 6.4 },
        radius: 4.2,
        phase: 0.1,
        angularSpeed: 0.28,
      },
      palette: { base: "#ff755e", accent: "#55214c", glow: "#ff967c" },
    },
    {
      id: "iron-dandelion",
      name: "铁蒲公英",
      role: "minor",
      position: { x: 14.6, y: 3.1 },
      mass: 2.57,
      radius: 1.12,
      captureRadius: 0,
      palette: { base: "#c8d1dc", accent: "#e07153", glow: "#ffb28a" },
    },
    {
      id: "silver-crown-chip",
      name: "白银碎冠",
      role: "minor",
      position: { x: 8.8, y: -7.0 },
      mass: 2.92,
      radius: 1.18,
      captureRadius: 0,
      palette: { base: "#dde9f4", accent: "#84eaff", glow: "#eef8ff" },
    },
    {
      id: "night-moss",
      name: "夜苔团",
      role: "minor",
      position: { x: 15.7, y: -13.4 },
      mass: 3.3,
      radius: 1.25,
      captureRadius: 0,
      palette: { base: "#345842", accent: "#b5ff8f", glow: "#9bff9f" },
    },
    {
      id: "plasma-bell",
      name: "电浆铃",
      role: "minor",
      position: { x: 21.0, y: -3.4 },
      mass: 3.72,
      radius: 1.31,
      captureRadius: 0,
      palette: { base: "#d48bff", accent: "#33e6ff", glow: "#e6b5ff" },
    },
    {
      id: "green-rivet",
      name: "绿焰铆",
      role: "minor",
      position: { x: 24.1, y: 6.7 },
      mass: 4.18,
      radius: 1.38,
      captureRadius: 0,
      palette: { base: "#9dff8d", accent: "#1f6d62", glow: "#b8ff9c" },
    },
    {
      id: "black-mirror",
      name: "黑面镜",
      role: "minor",
      position: { x: 27.8, y: -6.0 },
      mass: 4.68,
      radius: 1.44,
      captureRadius: 0,
      palette: { base: "#241c34", accent: "#ffca6a", glow: "#ce9aff" },
    },
    {
      id: "glass-well",
      name: "琉璃井",
      role: "minor",
      position: { x: 14.6, y: 11.7 },
      mass: 5.22,
      radius: 1.5,
      captureRadius: 0,
      palette: { base: "#ccfbff", accent: "#4d8dff", glow: "#dfffff" },
    },
    {
      id: "metal-moon",
      name: "金属月",
      role: "minor",
      position: { x: 30.6, y: 4.4 },
      mass: 5.8,
      radius: 1.56,
      captureRadius: 0,
      palette: { base: "#d6d9df", accent: "#f3d077", glow: "#fff0a0" },
    },
    {
      id: "deep-red-core",
      name: "深红核",
      role: "minor",
      position: { x: 22.6, y: -13.8 },
      mass: 6.42,
      radius: 1.62,
      captureRadius: 0,
      palette: { base: "#ff5f55", accent: "#3b1f46", glow: "#ff8f7e" },
    },
    {
      id: "avalanche-disk",
      name: "雪崩盘",
      role: "minor",
      position: { x: 31.1, y: -4.2 },
      mass: 7.08,
      radius: 1.68,
      captureRadius: 0,
      palette: { base: "#eef9ff", accent: "#6fb2ff", glow: "#f8ffff" },
    },
    {
      id: "violet-lock",
      name: "紫锁",
      role: "minor",
      position: { x: 25.8, y: 11.2 },
      mass: 7.78,
      radius: 1.74,
      captureRadius: 0,
      palette: { base: "#d39eff", accent: "#6442d8", glow: "#e3bdff" },
    },
    {
      id: "rust-reef",
      name: "锈礁",
      role: "minor",
      position: { x: 16.8, y: 14.7 },
      mass: 8.52,
      radius: 1.8,
      captureRadius: 0,
      palette: { base: "#c67d55", accent: "#f2df9b", glow: "#ffc48d" },
    },
    {
      id: "obsidian-heart",
      name: "黑曜心",
      role: "minor",
      position: { x: 30.0, y: 8.8 },
      mass: 9.3,
      radius: 1.86,
      captureRadius: 0,
      palette: { base: "#1d172c", accent: "#e962ff", glow: "#f08cff" },
    },
    {
      id: "tin-sun",
      name: "锡太阳",
      role: "minor",
      position: { x: 6.3, y: 15.2 },
      mass: 10.1,
      radius: 1.94,
      captureRadius: 0,
      palette: { base: "#f0f3db", accent: "#ffb061", glow: "#fff4ba" },
    },
    {
      id: "magenta-whale",
      name: "品红鲸",
      role: "minor",
      position: { x: 30.2, y: -14.0 },
      mass: 10.95,
      radius: 2.0,
      captureRadius: 0,
      palette: { base: "#ff80bd", accent: "#44245f", glow: "#ffa6d1" },
    },
  ],
};
