import type { LevelDefinition } from "../level";

export const LEVEL_01_GRAVITY_CHAIN: LevelDefinition = {
  id: "gravity-chain",
  name: "第一关：引力链",
  bounds: { x: 23.5, y: 13.2 },
  startPosition: { x: -21.2, y: -8.3 },
  startVelocity: { x: 3.85, y: 1.86 },
  goalMass: 6,
  goalShards: 5,
  planets: [
    {
      id: "qixia",
      name: "栖霞巨星",
      role: "anchor",
      position: { x: -11.6, y: -3.7 },
      mass: 6.8,
      radius: 1.86,
      captureRadius: 5.8,
      palette: { base: "#f7bd68", accent: "#ef5d63", glow: "#ffd47c" },
      hasRing: true,
    },
    {
      id: "ice-moon",
      name: "冰尘月",
      role: "minor",
      position: { x: -7.3, y: 1.25 },
      mass: 0.42,
      radius: 0.46,
      captureRadius: 0,
      palette: { base: "#b7f8ff", accent: "#6aa9ff", glow: "#8af5ff" },
    },
    {
      id: "amber-stone",
      name: "琥珀岩",
      role: "minor",
      position: { x: -2.35, y: 3.8 },
      mass: 0.58,
      radius: 0.56,
      captureRadius: 0,
      palette: { base: "#f8d28b", accent: "#d9823b", glow: "#ffe3a5" },
    },
    {
      id: "emerald-ring",
      name: "翡翠环星",
      role: "anchor",
      position: { x: 2.55, y: 5.25 },
      mass: 4.65,
      radius: 1.55,
      captureRadius: 6.15,
      palette: { base: "#7af2c0", accent: "#3b71ff", glow: "#75ffe6" },
      hasRing: true,
    },
    {
      id: "violet-chip",
      name: "紫晶碎星",
      role: "minor",
      position: { x: 7.65, y: 4.18 },
      mass: 0.82,
      radius: 0.62,
      captureRadius: 0,
      palette: { base: "#d8a8ff", accent: "#7e5cff", glow: "#d9b4ff" },
    },
    {
      id: "iron-seed",
      name: "铁种星",
      role: "minor",
      position: { x: 12.55, y: 0.05 },
      mass: 1.05,
      radius: 0.72,
      captureRadius: 0,
      palette: { base: "#bfc8d5", accent: "#e07153", glow: "#ffad80" },
    },
    {
      id: "tide-gate",
      name: "潮汐门",
      role: "anchor",
      position: { x: 9.25, y: -5.05 },
      mass: 2.75,
      radius: 1.17,
      captureRadius: 5.65,
      palette: { base: "#6cb8ff", accent: "#fff06a", glow: "#7bc7ff" },
    },
    {
      id: "moss-world",
      name: "苔原星",
      role: "minor",
      position: { x: 4.6, y: -9.18 },
      mass: 1.12,
      radius: 0.76,
      captureRadius: 0,
      palette: { base: "#95d986", accent: "#375b4d", glow: "#a7ff9d" },
    },
    {
      id: "ruby-core",
      name: "赤核",
      role: "minor",
      position: { x: -1.25, y: -7.75 },
      mass: 1.32,
      radius: 0.82,
      captureRadius: 0,
      palette: { base: "#ff755e", accent: "#691c36", glow: "#ff907c" },
    },
    {
      id: "silent-core",
      name: "静默核",
      role: "anchor",
      position: { x: -5.9, y: 7.5 },
      mass: 3.35,
      radius: 1.25,
      captureRadius: 4.95,
      palette: { base: "#f9f3dd", accent: "#5fcbd8", glow: "#fff7be" },
      hasRing: true,
    },
    {
      id: "obsidian-bloom",
      name: "黑曜花",
      role: "minor",
      position: { x: -11.4, y: 7.35 },
      mass: 1.55,
      radius: 0.9,
      captureRadius: 0,
      palette: { base: "#30264d", accent: "#e962ff", glow: "#ee77ff" },
    },
  ],
};
