import type { LevelDefinition } from "../level";

export const LEVEL_02_MANY_BODY_MAZE: LevelDefinition = {
  id: "many-body-maze",
  name: "第二关：群星迷航",
  bounds: { x: 26, y: 14.6 },
  startPosition: { x: -24.1, y: -10.4 },
  startVelocity: { x: 4.35, y: 2.1 },
  goalMass: 20,
  goalShards: 17,
  planets: [
    {
      id: "dawn-giant",
      name: "晨昏巨星",
      role: "anchor",
      position: { x: -14.2, y: -5.7 },
      mass: 12.8,
      radius: 2.08,
      captureRadius: 7.05,
      palette: { base: "#f2a35f", accent: "#e35c7a", glow: "#ffd077" },
      hasRing: true,
    },
    {
      id: "cyan-relay",
      name: "青辉中继",
      role: "anchor",
      position: { x: -7.7, y: 5.55 },
      mass: 15.4,
      radius: 1.82,
      captureRadius: 6.9,
      palette: { base: "#79f5df", accent: "#4668ff", glow: "#78ffef" },
      hasRing: true,
    },
    {
      id: "amber-well",
      name: "琥珀井",
      role: "anchor",
      position: { x: 0.45, y: -2.25 },
      mass: 16.9,
      radius: 1.62,
      captureRadius: 6.75,
      palette: { base: "#f8c36f", accent: "#8d4de8", glow: "#ffe09d" },
      hasRing: true,
    },
    {
      id: "white-core",
      name: "白昼核",
      role: "anchor",
      position: { x: -1.9, y: 9.25 },
      mass: 18.2,
      radius: 1.46,
      captureRadius: 5.75,
      palette: { base: "#fff5c6", accent: "#7ad8ff", glow: "#fff8b0" },
    },
    {
      id: "blue-gate",
      name: "蓝门",
      role: "anchor",
      position: { x: 8.25, y: 6.25 },
      mass: 22.4,
      radius: 1.38,
      captureRadius: 6.35,
      palette: { base: "#6aa9ff", accent: "#90ffcf", glow: "#77c9ff" },
      hasRing: true,
    },
    {
      id: "red-lock",
      name: "赤锁",
      role: "anchor",
      position: { x: 14.9, y: -4.75 },
      mass: 22.8,
      radius: 1.28,
      captureRadius: 6.65,
      palette: { base: "#ff7168", accent: "#5b1d56", glow: "#ff9a7f" },
    },
    {
      id: "dust-scout",
      name: "尘哨",
      role: "minor",
      position: { x: -18.25, y: -1.05 },
      mass: 0.34,
      radius: 0.4,
      captureRadius: 0,
      palette: { base: "#d8f8ff", accent: "#6aa9ff", glow: "#9df8ff" },
    },
    {
      id: "thin-ice",
      name: "薄冰星",
      role: "minor",
      position: { x: -10.2, y: -0.45 },
      mass: 0.48,
      radius: 0.46,
      captureRadius: 0,
      palette: { base: "#c8f7ff", accent: "#76a9ff", glow: "#b9f9ff" },
    },
    {
      id: "teal-grain",
      name: "青砂",
      role: "minor",
      position: { x: -8.95, y: -8.1 },
      mass: 0.62,
      radius: 0.52,
      captureRadius: 0,
      palette: { base: "#70f2c7", accent: "#1e7f9f", glow: "#7bffd9" },
    },
    {
      id: "rose-chip",
      name: "玫晶",
      role: "minor",
      position: { x: -3.8, y: -6.6 },
      mass: 0.78,
      radius: 0.58,
      captureRadius: 0,
      palette: { base: "#ff9db5", accent: "#8f2c75", glow: "#ffb4c7" },
    },
    {
      id: "basalt-pearl",
      name: "玄珠",
      role: "minor",
      position: { x: -12.8, y: 4.2 },
      mass: 0.92,
      radius: 0.64,
      captureRadius: 0,
      palette: { base: "#322b4f", accent: "#8af5ff", glow: "#a976ff" },
    },
    {
      id: "yellow-seed",
      name: "黄种",
      role: "minor",
      position: { x: -2.35, y: 2.05 },
      mass: 1.15,
      radius: 0.74,
      captureRadius: 0,
      palette: { base: "#ffe78a", accent: "#d9823b", glow: "#fff0a6" },
    },
    {
      id: "cobalt-eye",
      name: "钴眼",
      role: "minor",
      position: { x: 3.15, y: 2.75 },
      mass: 1.42,
      radius: 0.82,
      captureRadius: 0,
      palette: { base: "#5f7fff", accent: "#25d4ff", glow: "#86a2ff" },
    },
    {
      id: "moss-crown",
      name: "苔冠",
      role: "minor",
      position: { x: 4.35, y: -6.75 },
      mass: 1.65,
      radius: 0.88,
      captureRadius: 0,
      palette: { base: "#8bdc7c", accent: "#2f5f4a", glow: "#abff9e" },
    },
    {
      id: "ruby-drift",
      name: "赤漂",
      role: "minor",
      position: { x: 9.35, y: 0.65 },
      mass: 1.92,
      radius: 0.96,
      captureRadius: 0,
      palette: { base: "#ff775c", accent: "#691c36", glow: "#ff967c" },
    },
    {
      id: "iron-bell",
      name: "铁钟",
      role: "minor",
      position: { x: 11.8, y: 2.7 },
      mass: 2.35,
      radius: 1.06,
      captureRadius: 0,
      palette: { base: "#bfc8d5", accent: "#e07153", glow: "#ffad80" },
    },
    {
      id: "violet-dam",
      name: "紫堤",
      role: "minor",
      position: { x: 17.1, y: 1.0 },
      mass: 2.7,
      radius: 1.12,
      captureRadius: 0,
      palette: { base: "#d7a2ff", accent: "#6c45e8", glow: "#debaff" },
    },
    {
      id: "green-lantern",
      name: "绿灯",
      role: "minor",
      position: { x: 18.55, y: -9.2 },
      mass: 3.15,
      radius: 1.2,
      captureRadius: 0,
      palette: { base: "#9eff92", accent: "#2e6650", glow: "#b5ff9a" },
    },
    {
      id: "copper-reef",
      name: "铜礁",
      role: "minor",
      position: { x: 4.2, y: 9.7 },
      mass: 3.55,
      radius: 1.28,
      captureRadius: 0,
      palette: { base: "#d98d56", accent: "#f2db99", glow: "#ffc47f" },
    },
    {
      id: "night-orchid",
      name: "夜兰",
      role: "minor",
      position: { x: -9.95, y: 9.2 },
      mass: 2.15,
      radius: 1.0,
      captureRadius: 0,
      palette: { base: "#3b2a62", accent: "#e962ff", glow: "#f08cff" },
    },
    {
      id: "glass-lake",
      name: "镜湖",
      role: "minor",
      position: { x: 13.15, y: 8.85 },
      mass: 1.28,
      radius: 0.78,
      captureRadius: 0,
      palette: { base: "#c9fbff", accent: "#4d8dff", glow: "#d6ffff" },
    },
    {
      id: "black-bread",
      name: "黑面包",
      role: "minor",
      position: { x: -8.4, y: 10.8 },
      mass: 1.7,
      radius: 0.9,
      captureRadius: 0,
      palette: { base: "#261d38", accent: "#ffca6a", glow: "#ce9aff" },
    },
    {
      id: "silver-loom",
      name: "银织",
      role: "minor",
      position: { x: 21.0, y: -2.2 },
      mass: 2.95,
      radius: 1.16,
      captureRadius: 0,
      palette: { base: "#d6dde8", accent: "#7bd8ff", glow: "#eef7ff" },
    },
    {
      id: "sunken-core",
      name: "沉核",
      role: "minor",
      position: { x: 1.3, y: -8.65 },
      mass: 2.25,
      radius: 1.04,
      captureRadius: 0,
      palette: { base: "#f07d59", accent: "#332142", glow: "#ff9e7e" },
    },
    {
      id: "pale-drum",
      name: "苍鼓",
      role: "minor",
      position: { x: -6.4, y: 12.0 },
      mass: 0.86,
      radius: 0.62,
      captureRadius: 0,
      palette: { base: "#ebf5d5", accent: "#62c7d3", glow: "#f5ffc7" },
    },
  ],
};
